famous_people = [
    {"name": "Cristiano Ronaldo", "followers": 660, "profession": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "followers": 505, "profession": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "followers": 418, "profession": "Musician / Actress", "country": "USA"},
    {"name": "Dwayne Johnson", "followers": 394, "profession": "Actor / Former Wrestler", "country": "USA"},
    {"name": "Kylie Jenner", "followers": 393, "profession": "Media Personality / Businesswoman", "country": "USA"},
    {"name": "Ariana Grande", "followers": 375, "profession": "Musician / Actress", "country": "USA"},
    {"name": "Kim Kardashian", "followers": 358, "profession": "Media Personality / Businesswoman", "country": "USA"},
    {"name": "Beyoncé", "followers": 313, "profession": "Musician / Actress", "country": "USA"},
    {"name": "Khloé Kardashian", "followers": 304, "profession": "Media Personality", "country": "USA"},
    {"name": "Justin Bieber", "followers": 294, "profession": "Musician", "country": "Canada"},
    {"name": "Kendall Jenner", "followers": 287, "profession": "Model / Media Personality", "country": "USA"},
    {"name": "Taylor Swift", "followers": 281, "profession": "Musician", "country": "USA"},
    {"name": "Virat Kohli", "followers": 273, "profession": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "followers": 248, "profession": "Musician / Actress", "country": "USA"},
    {"name": "Neymar Jr.", "followers": 230, "profession": "Footballer", "country": "Brazil"},
    {"name": "Nicki Minaj", "followers": 225, "profession": "Musician", "country": "USA"},
    {"name": "Kourtney Kardashian", "followers": 218, "profession": "Media Personality", "country": "USA"},
    {"name": "Miley Cyrus", "followers": 213, "profession": "Musician / Actress", "country": "USA"},
    {"name": "Katy Perry", "followers": 204, "profession": "Musician", "country": "USA"},
    {"name": "Zendaya", "followers": 179, "profession": "Actress / Musician", "country": "USA"},
    {"name": "Kevin Hart", "followers": 176, "profession": "Comedian / Actor", "country": "USA"},
    {"name": "Cardi B", "followers": 163, "profession": "Musician", "country": "USA"},
    {"name": "LeBron James", "followers": 159, "profession": "Basketball Player", "country": "USA"},
    {"name": "Demi Lovato", "followers": 153, "profession": "Musician / Actress", "country": "USA"},
    {"name": "Rihanna", "followers": 149, "profession": "Musician / Entrepreneur", "country": "Barbados"},
    {"name": "Chris Brown", "followers": 144, "profession": "Musician", "country": "USA"},
    {"name": "Drake", "followers": 142, "profession": "Musician", "country": "Canada"},
    {"name": "Ellen DeGeneres", "followers": 135, "profession": "TV Host / Comedian", "country": "USA"},
    {"name": "Billie Eilish", "followers": 124, "profession": "Musician", "country": "USA"},
    {"name": "Kylian Mbappé", "followers": 123, "profession": "Footballer", "country": "France"},
    {"name": "Gal Gadot", "followers": 107, "profession": "Actress", "country": "Israel"},
    {"name": "Lisa (BLACKPINK)", "followers": 106, "profession": "Musician", "country": "Thailand"},
    {"name": "Vin Diesel", "followers": 103, "profession": "Actor", "country": "USA"},
    {"name": "Shraddha Kapoor", "followers": 94, "profession": "Actress", "country": "India"},
    {"name": "Narendra Modi", "followers": 94, "profession": "Prime Minister", "country": "India"},
    {"name": "Priyanka Chopra", "followers": 92, "profession": "Actress / Businesswoman", "country": "India"},
    {"name": "Shakira", "followers": 91, "profession": "Musician", "country": "Colombia"},
    {"name": "Snoop Dogg", "followers": 88, "profession": "Musician", "country": "USA"},
    {"name": "David Beckham", "followers": 88, "profession": "Former Footballer", "country": "UK"},
    {"name": "Dua Lipa", "followers": 87, "profession": "Musician", "country": "UK"},
    {"name": "Jennie (BLACKPINK)", "followers": 87, "profession": "Musician", "country": "South Korea"},
    {"name": "Alia Bhatt", "followers": 86, "profession": "Actress", "country": "India"}
]

